name: Super-Linter

# Run this workflow on both push and pull request events
on: [push, pull_request]

jobs:
  super-lint:
    name: Super-Linter
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Run the Super-Linter (latest slim version)
      - name: Run Super-Linter
        uses: github/super-linter/slim@v5
        env:
          # Lint the entire codebase every time
          VALIDATE_ALL_CODEBASE: true

          # Your main branch name
          DEFAULT_BRANCH: main

          # Required GitHub authentication token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
